version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    volumes:
      - db_data:/var/lib/mysql
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
    networks:
      - app-network

  php-app-1:
    build:
      context: ./php
    container_name: php-app-1
    depends_on:
      - db
    networks:
      - app-network

  php-app-2:
    build:
      context: ./php
    container_name: php-app-2
    depends_on:
      - db
    networks:
      - app-network

  php-app-3:
    build:
      context: ./php
    container_name: php-app-3
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx-lb
    ports:
      - "4500:4500"
    depends_on:
      - php-app-1
      - php-app-2
      - php-app-3
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
